name: Run Luma-Magento Create an Account, Login, Choose Product, View and Update Shopping Cart, Proceed to Checkout every 00:00 Time
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run Luma-Magento Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/web/magento/account/**.cy.js
      - name: Cypress run Luma-Magento Firefox
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          spec: cypress/e2e/web/magento/account/**.cy.js
      - name: Cypress run Luma-Magento Edge
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          spec: cypress/e2e/web/magento/account/**.cy.js
      - name: Cypress run Luma-Magento Chrome (Choose Product)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/web/magento/product/choose-product.cy.js
      - name: Cypress run Luma-Magento Firefox (Choose Product)
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          spec: cypress/e2e/web/magento/product/choose-product.cy.js
      - name: Cypress run Luma-Magento Edge (Choose Product)
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          spec: cypress/e2e/web/magento/product/choose-product.cy.js
      - name: Cypress run Luma-Magento Chrome (Checkout)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/web/magento/checkout/proceedCheckout.cy.js
      - name: Cypress run Luma-Magento Firefox (Checkout)
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          spec: cypress/e2e/web/magento/checkout/proceedCheckout.cy.js
      - name: Cypress run Luma-Magento Edge (Checkout)
        uses: cypress-io/github-action@v6
        with:
          browser: edge
          spec: cypress/e2e/web/magento/checkout/proceedCheckout.cy.js
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore